### ISSUE TITLE
[PATCH] Build fails with lightdm 1.19.3

### ISSUE THREAD

**Issue by bluesabre** [Xubuntu/lightdm-gtk-greeter#50]
lightdm-gtk-greeter.c: In function 'start_authentication':
lightdm-gtk-greeter.c:1935:9: error: too few arguments to function 'lightdm_greeter_authenticate'
         lightdm_greeter_authenticate (greeter, NULL);
         ^
In file included from /usr/include/lightdm-gobject-1/lightdm.h:14:0,
                 from lightdm-gtk-greeter.c:48:
/usr/include/lightdm-gobject-1/lightdm/greeter.h:151:10: note: declared here
 gboolean lightdm_greeter_authenticate (LightDMGreeter *greeter, const gchar *username, GError **error);
          ^
lightdm-gtk-greeter.c:1939:9: error: too few arguments to function 'lightdm_greeter_authenticate_as_guest'
         lightdm_greeter_authenticate_as_guest (greeter);
         ^
In file included from /usr/include/lightdm-gobject-1/lightdm.h:14:0,
                 from lightdm-gtk-greeter.c:48:
/usr/include/lightdm-gobject-1/lightdm/greeter.h:153:10: note: declared here
 gboolean lightdm_greeter_authenticate_as_guest (LightDMGreeter *greeter, GError **error);
          ^
lightdm-gtk-greeter.c:1959:9: error: too few arguments to function 'lightdm_greeter_authenticate'
         lightdm_greeter_authenticate (greeter, username);
         ^
In file included from /usr/include/lightdm-gobject-1/lightdm.h:14:0,
                 from lightdm-gtk-greeter.c:48:
/usr/include/lightdm-gobject-1/lightdm/greeter.h:151:10: note: declared here
 gboolean lightdm_greeter_authenticate (LightDMGreeter *greeter, const gchar *username, GError **error);
          ^
lightdm-gtk-greeter.c: In function 'cancel_authentication':
lightdm-gtk-greeter.c:1981:9: error: too few arguments to function 'lightdm_greeter_cancel_authentication'
         lightdm_greeter_cancel_authentication (greeter);
         ^
In file included from /usr/include/lightdm-gobject-1/lightdm.h:14:0,
                 from lightdm-gtk-greeter.c:48:
/usr/include/lightdm-gobject-1/lightdm/greeter.h:161:10: note: declared here
 gboolean lightdm_greeter_cancel_authentication (LightDMGreeter *greeter, GError **error);
          ^
lightdm-gtk-greeter.c: In function 'start_session':
lightdm-gtk-greeter.c:2015:9: error: too few arguments to function 'lightdm_greeter_set_language'
         lightdm_greeter_set_language (greeter, language);
         ^
In file included from /usr/include/lightdm-gobject-1/lightdm.h:14:0,
                 from lightdm-gtk-greeter.c:48:
/usr/include/lightdm-gobject-1/lightdm/greeter.h:169:10: note: declared here
 gboolean lightdm_greeter_set_language (LightDMGreeter *greeter, const gchar *language, GError **error);
          ^
lightdm-gtk-greeter.c: In function 'login_cb':
lightdm-gtk-greeter.c:2236:9: error: too few arguments to function 'lightdm_greeter_respond'
         lightdm_greeter_respond (greeter, gtk_entry_get_text (password_entry));
         ^
In file included from /usr/include/lightdm-gobject-1/lightdm.h:14:0,
                 from lightdm-gtk-greeter.c:48:
/usr/include/lightdm-gobject-1/lightdm/greeter.h:159:10: note: declared here
 gboolean lightdm_greeter_respond (LightDMGreeter *greeter, const gchar *response, GError **error);
          ^
lightdm-gtk-greeter.c: In function 'timed_autologin_cb':
lightdm-gtk-greeter.c:2329:13: error: too few arguments to function 'lightdm_greeter_authenticate_autologin'
             lightdm_greeter_authenticate_autologin (greeter);
             ^
In file included from /usr/include/lightdm-gobject-1/lightdm.h:14:0,
                 from lightdm-gtk-greeter.c:48:
/usr/include/lightdm-gobject-1/lightdm/greeter.h:155:10: note: declared here
 gboolean lightdm_greeter_authenticate_autologin (LightDMGreeter *greeter, GError **error);

Launchpad Details: [#LP1606183](https://bugs.launchpad.net/bugs/1606183) rezso - 2016-07-25 10:26:56 +0000

**Comment by bluesabre** [comment]
Same errors with lightdm 1.18.2.

Launchpad Details: [#LPC](https://bugs.launchpad.net/lightdm-gtk-greeter/+bug/1606183/comments/1) rezso - 2016-07-26 02:58:09 +0000

**Comment by bluesabre** [comment]
with 1.18.2 it builds okay

Launchpad Details: [#LPC](https://bugs.launchpad.net/lightdm-gtk-greeter/+bug/1606183/comments/2) Alex - 2016-07-26 05:04:52 +0000

**Comment by bluesabre** [comment]
Yes, this was my mistake, I forgot to delete the previously built 1.19.3.
But with a small patch I fixed the build with 1.19.3.

Launchpad Details: [#LPC](https://bugs.launchpad.net/lightdm-gtk-greeter/+bug/1606183/comments/3) rezso - 2016-07-26 05:21:35 +0000

**Comment by bluesabre** [comment]
A patch can be found here:

https://bugs.gentoo.org/show_bug.cgi?id=588764



Launchpad Details: [#LPC](https://bugs.launchpad.net/lightdm-gtk-greeter/+bug/1606183/comments/4) Sven Eden - 2016-08-12 11:19:47 +0000

**Comment by rezso** [comment]
Fixed in https://github.com/Xubuntu/lightdm-gtk-greeter/commit/7972a4e2c445875126610e02820dd6d8c51d19f4

**Comment by bluesabre** [comment]
Thanks for that note @rezso!
